Adding `--date' argument to configure time format
mike-engel/jwt-cli pull request #235
Opened 2023-01-24 20:10 UTC by jazcarate

### Summary
`--iso8601` was too hard for me to remember, and most often than not I want to see the time in my local timezone

### Preflight checklist
- [x] Code formatted with rustfmt
- [x] Relevant tests added
- [x] Any new documentation added

2023-02-04 16:02 UTC, mike-engel requested changes

2023-02-07 20:51 UTC, jazcarate commented on src/cli_config.rs
> +                    None => panic!("Should have been able to parse the offset"),
This panic should never ever happen. The format (`%#z`) is an _offset_ format, so there is *no way* `parsed.offset` is a `None`.
For example, a format like `"%H:%M:%S"` has a `None` `offset`.

The error when you input something that is not an offset is the `Err(_)` in the next line

2023-02-08 08:38 UTC, mike-engel commented on src/cli_config.rs
> +    /// Use --date for finer control
The next version will be a major bump anyway, so this is a good opportunity to keep the tool simple

2023-02-15 17:37 UTC, jazcarate commented on src/cli_config.rs
> +    /// Use --date for finer control
Removed 😃

2023-02-16 15:38 UTC, mike-engel approved these changes

2023-02-16 15:39 UTC, merged

2023-06-22 20:56 UTC, mike-engel commented
Very sorry for the delay, but this is in [6.0.0](https://github.com/mike-engel/jwt-cli/releases/tag/6.0.0) now